### ISSUE TITLE
JST Connectors for PZEMs

### ISSUE THREAD

**Issue by rosscullen** [Fionnoch/ESPHome_PZEM_Monitoring#1]
Thanks @Fionnoch for great tutorial on YouTube. As I mentioned, tried to order cables a number of times but after 3 attempts, the wrong width connectors keep arriving :-( Any chance I can get you to make up 4 or 5 pairs please 🙏 ? Much appreciated 😊

**Comment by rosscullen** [comment]
![20231022_122359.jpg](https://github.com/Fionnoch/ESPHome_PZEM_Monitoring/assets/35301905/38ab92e6-9d46-47ae-9da0-59391bc9de16)

Example pic... so near and yet so far!

**Comment by Fionnoch** [comment]
Ah damn thats very annoying! I've never had that issue before when buying. 

If you send me a mail on fionnoch@msn.com we can chat about what you need. Thats my spam email so I don't mind it being on the web but I will probably delete this message after in a while just to be on the safe side

**Comment by rosscullen** [comment]
Thanks for details. Will contact you shortly and if we find the link or specific model etc, we can post details. Closing issue for now. Thanks @Fionnoch
